# Generated by Django 5.0.6 on 2024-06-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_age_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_created',
        ),
    ]
